name: Deploy to develop
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull Code
        uses: actions/checkout@v3
      - name: Setup Environment
        run: |
          echo "${{ toJSON(github.env) }}"
          cat "${{ toJSON(github.env) }}"
      - name: Build artifacts
        run: |
          yarn install
          yarn generate
